web/src/components/torrents/TorrentDetailsPanel.tsx, web/src/pages/Torrents.tsx
- Add proper overflow handling and height constraints
- Restructure TabsContent with individual ScrollArea components
- Disable Sheet slide animations to prevent animation hang on polls
=> fix(web): resolve scrolling issues in torrent details panel tabs

.air.toml, .goreleaser.yml, CLAUDE.md, Dockerfile, Makefile, README.md, ci.Dockerfile, cmd/qui/main.go, internal/config/config.go, internal/config/config_test.go, prd_final.md
Run the server from `serve` subcommnad, to allow for other subcommands in the future.
=> feat: run from `serve` subcommand

web/src/components/instances/InstanceCard.tsx, web/src/pages/Dashboard.tsx
=> fix(web): instance URL overflow

web/src/components/torrents/FilterSidebar.tsx
This adds the ability to clear each filter on it's own and not just all filters all at once.
=> feat(filters): clear each filter separately

internal/api/handlers/auth.go, internal/api/handlers/instances.go, internal/api/middleware/auth.go, internal/auth/service.go, internal/database/db.go, internal/database/db_test.go, internal/models/api_key.go, internal/models/instance.go, internal/models/instance_test.go, internal/models/user.go, internal/qbittorrent/pool.go, internal/qbittorrent/sync_manager.go
Pass context everywhere from http handlers to database interactions etc.
=> feat: pass context everywhere

web/eslint.config.js, web/package.json, web/pnpm-lock.yaml
Based on https://github.com/autobrr/autobrr/pull/1327
=> chore(lint): add eslint rules

CLAUDE.md, Dockerfile, README.md, ci.Dockerfile, docker-compose.yml, internal/config/config.go, internal/web/swagger/openapi.yaml, prd_final.md, web/vite.config.ts
=> refactor(config): change default port from 8080 to 7476

web/src/components/instances/InstanceCard.tsx, web/src/components/instances/InstanceErrorDisplay.tsx, web/src/components/instances/PasswordIssuesBanner.tsx, web/src/pages/Dashboard.tsx, web/src/pages/Instances.tsx
- Extract PasswordIssuesBanner component for reusable password error alerts
- Extract InstanceErrorDisplay component for consistent error handling
- Refactor InstanceCard to use new InstanceErrorDisplay component
- Update Dashboard to show error states with navigation to instances page
- Add PasswordIssuesBanner to both Dashboard and Instances pages
- Improve error visibility across the application
This refactoring eliminates code duplication while adding better error visibility to the Dashboard page, making it easier for users to identify and resolve instance connection issues.
=> refactor(web): extract error display components

internal/web/handler.go, web/src/components/torrents/TorrentDialogs.tsx, web/src/components/ui/table.tsx
Enhanced serveSPA and serveAssets functions to properly handle static asset paths when using custom base URL configuration. Fixes 404 errors for favicon.png, apple-touch-icon.png, registerSW.js, and PWA manifest files. Includes dynamic content modification for service worker files and proper manifest.webmanifest path handling.
=> fix(web): resolve static asset routing with custom base URL

web/src/components/Footer.tsx, web/src/components/layout/Sidebar.tsx, web/src/pages/Login.tsx, web/src/pages/Setup.tsx
- Add Footer component with copyright and GitHub link
- Update Login page styling with centered branding and proper card styling
- Modernize Setup page to match Login page design consistency
- Refactor error message styling with better visual feedback
- Add responsive padding and improved button sizing
- Maintain consistent typography and spacing across auth pages
=> feat(web): improve login and setup page UI design

web/src/components/torrents/TorrentCardsMobile.tsx, web/src/components/torrents/TorrentTableOptimized.tsx
This changes the behavior of the `TorrentCardsMobile` component to mirror the `TorrentTableOptimized` component when using select all.
=> fix(web/mobile): select all only selects 500 torrents

web/src/components/torrents/FilterSidebar.tsx, web/src/components/torrents/TorrentTableOptimized.tsx, web/src/components/ui/SearchInput.tsx, web/src/hooks/useTorrentsList.ts, web/src/lib/incognito.ts, web/src/types/index.ts
- Add user action tracking to differentiate user changes from automatic data updates
- Fix pagination with proper hasMore handling from backend response
- Add debouncing to prevent race conditions during rapid scroll events
- Cap loadedRows to actual data length to keep UI counters accurate
- Implement conditional scroll resets (only on user actions, not data updates)
- Improve virtual scrolling stability with torrent hash-based keys
- Prevent excessive API requests with request timing controls
=> fix(web): resolve scroll position reset issues

README.md, cmd/qui/main.go, internal/config/config.go, internal/domain/config.go
- Add MetricsEnabled bool field to Config struct
- Set default to false
- Add QUI__METRICS_ENABLED environment variable support
- Update config template with metrics documentation
- Update README
=> feat(config): add metricsEnabled configuration option

web/src/components/themes/ThemeLicenseManager.tsx, web/src/components/themes/ThemeValidator.tsx, web/src/hooks/useThemeLicense.ts, web/src/lib/theme-license-errors.ts, web/src/pages/Settings.tsx
- Redesign ThemeLicenseManager with cleaner, integrated UI
- Rename hooks for clarity (usePremiumAccess, useLicenseDetails)
- Add centralized error message handling
- Add license key masking
- Reduce cache stale time from 30min to 5min
- Reorder settings tabs for better flow
=> refactor(web): simplify theme licensing UX and hook names

internal/qbittorrent/sync_manager.go
Adds custom sorting for priority field to show queued torrents (1+) before non-queued (0)
Correctly handle qBittorrent queue positions where 0 = not queued
=> fix(qbittorrent): sort queued torrents

web/src/pages/NotFound.tsx, web/src/routes/__root.tsx
=> feat(web): add NotFound page

internal/qbittorrent/sync_manager.go
Reduces from 15 seconds, to 15ms, roughly.
=> feat(filtering): use maps for lookups

internal/api/handlers/auth.go, internal/api/router.go, web/src/hooks/useAuth.ts, web/src/pages/Login.tsx, web/src/pages/Setup.tsx
- Remove async validation that blocked submit button during debounce
- Add session warming to prefetch data after login
- Skip prefetching on initial setup (no instances exist yet)
=> fix(auth): improve login form UX and add session warming

go.mod, go.sum
Pulls in https://github.com/autobrr/go-qbittorrent/commit/79e00669bb9b66cf7f1d4a8d21adc069e55a59b8
Needed for #272
=> chore(deps): bump go-qbittorrent

web/src/components/torrents/TorrentCardsMobile.tsx, web/src/components/torrents/TorrentTableColumns.tsx
=> fix(web): truncate near-complete progress decimals

web/src/components/settings/ClientApiKeysManager.tsx, web/src/components/themes/LicenseManager.tsx, web/src/components/torrents/TorrentContextMenu.tsx, web/src/components/torrents/TorrentDetailsPanel.tsx, web/src/lib/utils.ts, web/src/pages/Settings.tsx
=> fix(web): add clipboard fallback for non-HTTPS contexts

go.mod, go.sum, internal/qbittorrent/sync_manager.go
Re: https://github.com/autobrr/go-qbittorrent/pull/83
Supersedes #337
Closes #323
=> fix(filter): ensure tag filters require exact matches

internal/api/handlers/torrents.go, internal/api/handlers/torrents_test.go, internal/api/server.go, internal/qbittorrent/sync_manager.go, internal/web/swagger/openapi.yaml, web/src/components/torrents/TorrentContextMenu.tsx, web/src/components/torrents/TorrentTableOptimized.tsx, web/src/hooks/useTorrentExporter.ts, web/src/lib/api.ts
`[domain] ReleaseName - ShortHash.torrent`
=> feat(torrent): add export logic

web/src/components/torrents/FilterSidebar.tsx
keep tags, categories, and trackers in their original ordering when toggled
=> fix(filters): keep toggleable lists in original order

web/src/components/torrents/TorrentTableColumns.tsx, web/src/components/torrents/TorrentTableOptimized.tsx
This should get rid of the flickering of the icons
=> fix(web): stabilize tracker icons in torrent table

go.mod, go.sum, internal/api/handlers/capabilities.go, internal/api/handlers/instances.go, internal/api/handlers/torrents.go, internal/api/server.go, internal/qbittorrent/client.go, internal/qbittorrent/sync_manager.go, internal/web/swagger/openapi.yaml, internal/web/swagger/openapi_test.go, web/src/components/layout/Header.tsx, web/src/components/torrents/TorrentCardsMobile.tsx, web/src/components/torrents/TorrentContextMenu.tsx, web/src/components/torrents/TorrentCreationTasks.tsx, web/src/components/torrents/TorrentCreatorDialog.tsx, web/src/components/torrents/TorrentManagementBar.tsx, web/src/components/torrents/TorrentTableOptimized.tsx, web/src/components/torrents/TorrentTableResponsive.tsx, web/src/components/torrents/piece-size.ts, web/src/components/ui/context-menu.tsx, web/src/hooks/useTorrentsList.ts, web/src/lib/api.ts, web/src/lib/torrent-task-polling.ts, web/src/pages/Torrents.tsx, web/src/routes/_authenticated/instances.$instanceId.tsx, web/src/types/index.ts
Adds native Torrent Creator
Works for qBittorrent v5+
TODO:
Targets [autobrr/go-qbittorrent@`9150109` (#85)](https://github.com/autobrr/go-qbittorrent/pull/85/commits/9150109e3685c1a296a3ce9002f890002bf2e380)
Screenshots:
=> feat(torrents): create torrents

web/src/components/torrents/TorrentCreationTasks.tsx, web/src/hooks/useDateTimeFormatters.ts, web/src/lib/dateTimeUtils.ts
update torrent creation tasks to use date/time settings
=> fix(web): sync torrent creation dates to preferences

web/src/App.tsx, web/src/components/ui/tooltip.tsx
=> fix(web): mobile tooltips
