autobrr/qui

README.md
This PR adapts the README.md so that the grep command only looks for `browser_download_url` so that i won't pick up the word `download` in the release message which makes the consequent grep command fail.
Also added a note for the extract command which needs root / sudo to successfully run.
=> fix(docs): quick install instructions

.gitignore, internal/config/config.go, internal/database/db.go, internal/database/migrations/003_add_basic_auth.sql
- Explicitly set database path immediately after creating new config file
- Add proper error handling when reading newly created config
- Improve logging to track database and config path initialization
- Add verification that database file is actually created
This fixes the issue where the database file would not be created on first start in Docker containers, requiring a restart to work properly.
=> fix: resolve Docker database initialization issue on first start

web/src/components/torrents/FilterSidebar.tsx, web/src/components/torrents/TorrentTableOptimized.tsx, web/src/components/torrents/TorrentTableResponsive.tsx, web/src/hooks/usePersistedFilterSidebarState.ts, web/src/pages/Torrents.tsx
- Add collapsible FilterSidebar that slides in/out smoothly
- Implement persistent collapsed state using localStorage
- Add filter toggle button in table toolbar next to search bar
- Memoize FilterSidebar component to prevent animation breaks during polling
- Add text truncation for long category/tag/tracker names
- Show active filter indicator on toggle button
The FilterSidebar now has a clean slide animation and maintains state across page refreshes. The toggle button is consistently positioned in the toolbar for easy access.
=> feat: add collapsible filter sidebar with smooth animations

web/src/components/torrents/TorrentTableOptimized.tsx, web/src/hooks/useTorrentsList.ts, web/src/lib/utils.ts, web/src/pages/Dashboard.tsx, web/src/types/index.ts
- Display user statistics (downloaded/uploaded/ratio/peers) on individual instance pages
- Add combined all-time statistics for all instances on dashboard
- Fetch serverState data using syncMainData API endpoint
- Create reusable getRatioColor() utility function to eliminate code duplication
=> feat: add all-time statistics display across application

web/src/components/torrents/TorrentTableOptimized.tsx, web/src/pages/Dashboard.tsx
- Blur instance URLs on dashboard when incognito mode is enabled
- Add eye toggle button to reveal/hide individual URLs
- Consistent icon usage: EyeOff when hidden, Eye when visible
- Addresses issue #11 for privacy protection
=> feat: add URL masking in incognito mode for dashboard

internal/config/config.go
Switches from `AutomaticEnv()` to explicit `BindEnv()` calls to prevent conflicts with K8s environment variables.
**Breaking change:** Only uppercase env vars (`QUI__HOST`) work now, not lowercase (`qui__host`).
**No impact on config.toml** - file-based configuration unchanged.
=> fix: use explicit env var binding to prevent K8s conflicts

cmd/server/main.go, internal/config/config.go, internal/domain/config.go
Add command line flag to enable pprof server. The flag overrides config file and environment variable settings.
Usage: qui --pprof
=> feat: add --pprof command line flag

web/src/components/layout/Sidebar.tsx
Adds copyright notice and GitHub link to sidebar footer
=> feat(web): add footer attribution to sidebar

web/src/components/torrents/FilterSidebar.tsx, web/src/pages/Torrents.tsx
Use the already defined `Category` type instead of redefining the type inline.
=> refactor(torrents): reuse existing type definition

.github/workflows/release.yml
Remove hardcoded GO_VERSION environment variable and use go-version-file to read version from go.mod instead.
=> chore(ci): use go.mod for Go version in release workflow

go.mod, go.sum, internal/qbittorrent/client.go, internal/qbittorrent/sync_manager.go
Adds proactive WebAPI version checking to determine SetTags support before API calls, with automatic fallback to RemoveTags + AddTags for older qBittorrent versions (< 5.1).
- Cache WebAPI version during client initialization  
- Check version support before SetTags calls
- Fallback to RemoveTags + AddTags for unsupported versions
- Add semver dependency for reliable version comparison
Fixes #74
=> feat(qbittorrent): add version-aware SetTags fallback

internal/api/handlers/instances.go, internal/config/config.go, internal/qbittorrent/pool.go, web/src/components/instances/InstanceCard.tsx, web/src/components/ui/alert.tsx, web/src/lib/base-url.ts, web/src/pages/Instances.tsx, web/src/types/index.ts
- Add warning comments to config template about sessionSecret changes
- Implement smart error logging to reduce spam for decryption failures
- Add decryption error tracking in ClientPool to log only once per instance
- Expose decryption error status via API for frontend handling
- Add user-friendly "Password Required" UI prompts in instance cards
- Add global banner on instances page when decryption errors exist
- Hide redundant connection errors when showing password prompts
- Fix card height stretching issue with items-start grid alignment
- Add shadcn/ui Alert component for better messaging
- Use proper semantic theme colors for error states
The solution provides clear recovery path for users when sessionSecret changes.
=> fix(auth): improve sessionSecret change handling with better UX

cmd/qui/main.go, go.mod, go.sum, internal/api/handlers/instances.go, internal/qbittorrent/client.go, internal/qbittorrent/pool.go, internal/qbittorrent/pool_test.go, web/src/components/instances/InstanceCard.tsx, web/src/components/instances/InstanceErrorDisplay.tsx, web/src/components/instances/InstanceForm.tsx, web/src/pages/Dashboard.tsx, web/src/pages/Instances.tsx
Implements async instance operations to prevent UI freezing when connecting to slow/unresponsive qBittorrent instances. Replaces global locks with per-instance locking and adds collapsible error displays.
- Async create/update: Operations return immediately after database save
- Per-instance locking: Prevents one slow instance from blocking others  
- Background connection testing: Non-blocking with 30-second timeouts
- Collapsible error display: Replace tooltips with expandable error cards
- Single connection status source: Eliminate inconsistencies across components
- Startup client initialization: Pre-connect to instances on app start
Before: Adding non-responding instances froze UI for 30+ seconds
After: Instant responses, background testing, working instances unaffected
=> feat(api,web): async instance operations with non-blocking UI

web/src/components/torrents/TagCategoryManagement.tsx
Fixes spacing issues in the dialogs that prompt for editing or adding categories and tags.
Before
After
=> fix(web): spacing in tags and category dialog

web/src/components/torrents/FilterSidebar.tsx, web/src/components/torrents/TagCategoryManagement.tsx, web/src/lib/api.ts, web/src/types/index.ts
This improves the category edit dialog to also show the old save path.
Before
After
=> feat(web): better category edit dialog

web/src/components/torrents/TorrentTableOptimized.tsx, web/src/hooks/useTorrentsList.ts, web/src/pages/Torrents.tsx
This resolves the FilterSidebar flashing during pagination calls, mostly noticeable during fast scrolling.
- keep torrent filter metadata around while pagination fetches run so the sidebar no longer flashes empty state
- gate TorrentTable callbacks behind metadata diffs to avoid redundant sidebar renders
- reuse the previous page response as placeholder data while React Query loads the next slice, keeping TanStack Virtual stable
=> perf(torrents): smooth sidebar during pagination

web/src/components/torrents/TorrentTableOptimized.tsx, web/src/hooks/useTorrentsList.ts
Clears torrent lists when filters return zero results
- update `useTorrentsList` to skip first-page placeholder data and clear cached rows when a filter returns zero results
- align the empty-table overlay with the loading overlay so the blank state message appears in the same absolute layer without a background blur
=> fix(web): clear stale torrents on empty state

web/src/components/torrents/TorrentCardsMobile.tsx
Lift the mobile `ScrollToTopButton` to avoid overlap with the bottom navigation
=> fix(web): raise mobile scroll button

internal/api/server.go, internal/web/handler.go
Respect baseUrl when serving web UI
- mount the embedded frontend router beneath the configured baseUrl so `/qui/assets/...` resolves correctly
- add an explicit SPA root handler to serve `index.html` for both `/qui` and `/qui/`
=> fix(server): respect baseUrl when serving web UI

web/src/lib/utils.ts
- ensure `formatErrorMessage` safely handles undefined and empty inputs
- prevent instance toasts from crashing when backend omits an error string
=> fix(web): guard undefined instance error messages

internal/api/handlers/client_api_keys.go, web/src/components/settings/ClientApiKeysManager.tsx, web/src/lib/api.ts
Refactor client API key instructions rendering
- remove backend-generated instructions for client API keys and rely on proxy URL payload
- render tailored setup guidance in the UI based on client name with richer formatting
- adjust API typings and dialog copy to match the simplified server response
Old:
New:
=> refactor(client-api-keys): derive proxy instructions client-side

web/src/components/torrents/TorrentContextMenu.tsx, web/src/components/torrents/TorrentDetailsPanel.tsx, web/src/lib/torrent-utils.ts
Fix:
- centralize torrent hash normalization so v1/v2 fields fall back to the legacy hash when servers omit them
- reuse the helper in the details panel and context menu so copy + display work on qBittorrent 4.3.x without extra API calls
New:
- keep the peers query tab-gated while leaving existing reopen behavior untouched
=> fix(web): normalize torrent hash fallbacks

web/src/components/torrents/TorrentDetailsPanel.tsx, web/src/lib/linkUtils.tsx
- Adjusts `created_by` field to present clickable links - useful when applications inject links into this field.
- Fixes link regex to remove trailing brackets noticed, with above.
=> fix(web): remove trailing punctuation from clickable links

web/src/components/torrents/TorrentTableOptimized.tsx
This removes the blue dot at the top of the column toggle button, because it was getting people confused.
Before:
After:
=> fix(header): columns toggle remove blue dot

go.mod, go.sum, web/src/components/torrents/TorrentDialogs.tsx, web/src/components/torrents/TorrentManagementBar.tsx, web/src/components/torrents/TorrentTableOptimized.tsx, web/src/types/index.ts
- preload share and speed limit dialogs with the selected torrents' current values and add a global limits toggle
- send qBittorrent's expected sentinel values when toggles are disabled, fixing the silent speed limit failure
- pass torrent snapshots into the dialogs, extend the torrent type definitions, and bump go-qbittorrent to expose the new fields
New global limit override:
=> fix(torrents): preload limit dialogs with current values

web/src/components/torrents/TorrentTableOptimized.tsx, web/src/hooks/usePersistedColumnSizing.ts
- scope torrent table column sizing keys by instance to keep settings isolated
- migrate any legacy global sizing values when an instance-specific key is available
- pass the active instance id through the torrent table so widths persist correctly per view
=> fix(web): scope column widths per instance

web/src/lib/column-filter-utils.ts
Allow users to filter `progress` using percentages instead of fractions
=> fix(web): accept percentage values for progress filters

web/src/components/torrents/ColumnFilterPopover.tsx, web/src/components/ui/button.tsx, web/src/lib/column-constants.ts, web/src/lib/column-filter-utils.ts
This brings several improvements to the column filtering, adding unit selection for speed, a dropdown for selecting a state, a case sensitivity toggle for strings and a clearer indication that you are filtering a percentage in the progress column.
Additionally fixes a bug where clicking and holding left click and moving your cursor inside the popover would drag the column.
=> feat(torrents): improvements to column filtering
